name: 'WeComBot-action'
description: 'Send messages via WeCom Bot'
branding:
  icon: 'message-circle'
  color: 'gray-dark'
inputs:
  bot-url:
    description: 'The URL of WeCom Bot'
    required: true
  text-message:
    description: 'The text message to be sent'
    default: "Empty message"
    required: true
outputs:
  response:
    description: 'The response from WeCom Bot HTTP Api'
runs:
  using: 'node16'
  main: 'dist/index.js'